# taken from https://github.com/kadnan/DockerPHPTutorial
version: '2'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql-server-57
    command: --default-authentication-plugin=mysql_native_password
    working_dir: /application
    volumes:
      - .:/application
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=myrootpwd
      - MYSQL_DATABASE=proteas
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbpwd
  app:
    container_name: proteas
    build:
      context: ./
    links:
      - "mysql:database"
    volumes:
      - ./:/var/www/html
    ports:
      - 80:80
    depends_on:
      - mysql
